name: Flox Built Cache Integration
description: Updates Built Cache State by evaluating the specified attribute and pushing the evaluation results to an AWS bucket
inputs:

  attr_path:
    description: "Attribute to be evaluated"
    required: true
    default: "packages.x86_64-linux.default"
  flake_ref:
    description: "Target flakeref"
    required: true
    default: .
  
  aws_bucket:
    description: "AWS S3 Bucket that holds evaluation results"
    required: true
    default: "versions-cache"
  aws_access_key_id:
    required: true
    description: Your AWS access key
  aws_secret_access_key:
    required: true
    description: Your AWS secret access key
 
  git_token:
    required: false
    description: Git token to be used to authenticate access to private Git repositories on GitHub
  
  substituter:
    required: false
    description: Your custom build cache used by the capacitpr to check build results


runs:
  using: composite
  steps:
    - id: config
      shell: bash
      run: |
        # FIXME: make generic over github instances (GH Enterprise)
        # TODO: use `?ref=..`
        FLAKE_REF="github:${{github.repository}}/${{github.ref_name}}#${{inputs.attr_path}}"
        FLAKE_REF="$(echo ${FLAKE_REF} | tr / _)"
        DB_PATH="$FLAKE_REF.db"
        EVAL_RESULT="$FLAKE_REF.json"


        echo "::set-output name=flake-ref-file-name::${FLAKE_REF}"
        echo "::set-output name=db-path::${DB_PATH}"
        echo "::set-output name=eval-result::${EVAL_RESULT}"

    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = ${{ inputs.git_token }}
          extra-substituters = s3://flox-store-public
          extra-trusted-public-keys = flox-store-public-0:8c/B+kjIaQ+BloCmNkRUKwaVPFWkriSAd0JJvuDu4F0=

    - shell: bash
      env:
        FLOX_FLAKE_REF: ${{inputs.flake_ref}}
        FLOX_ATTR_PATH: ${{inputs.attr_path}}
        FLOX_CACHE_DB_PATH: ${{steps.config.outputs.db-path}}
        FLOX_EVAL_RESULT: ${{steps.config.outputs.eval-result}}
        FLOX_ALT_SUBSTITUTER: ${{inputs.substituter}} 
        FLOX_AWS_BUCKET: ${{inputs.aws_bucket}}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_REGION: us-east-1
      run: |
        nix run github:flox/flox-integration-action#ci
